name: FABRICATION AGRO ERP
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installation de Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Reparation et Creation du moteur Gradle
        run: |
          # Cette partie crée les fichiers manquants automatiquement
          gradle wrapper --gradle-version 8.0
          chmod +x gradlew

      - name: Fabrication de l'APK (AGRO ERP)
        run: ./gradlew assembleDebug --stacktrace

      - name: Telechargement de l'APK final
        uses: actions/upload-artifact@v3
        with:
          name: AGRO-ERP-V1-INSTALLABLE
          path: app/build/outputs/apk/debug/app-debug.apk
