name: FABRICATION-APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Installer Gradle (le fabriquant)
        run: |
          sudo apt-get install gradle
          gradle wrapper --gradle-version 8.0

      - name: Donner les permissions
        run: chmod +x gradlew

      - name: Fabriquer l'APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Livrer l'APK
        uses: actions/upload-artifact@v3
        with:
          name: AGRO-ERP-INSTALLABLE
          path: app/build/outputs/apk/debug/app-debug.apk
